site_name: vhs-decode
site_description: vhs-decode documentation

theme:
  name: readthedocs

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - markdown.extensions.admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

nav:
  - Home:
      - Home: index.md
  #      - Press & Media: press_and_media.md
  - Starting & Contributing:
      - FAQ - Frequently Asked Questions: faq.md
#      - Diagram Breakdowns: Diagram-Visuals.md
#      - Visual-Comparisons: Visual-Comparisons.md
#      - VCR Reports: VCR-reports.md
#      - RF Tap Examples: 004-The-Tap-List.md
#      - Download & Contribute Data: Submitting-&-Downloading-Sample-Data.md
#      - Speed Testing: Speed-Testing.md
